---
# Install sonarqube packages

- name: unwanted packages are removed
  package:
    name: "{{ sonarqube_packages_remove }}"
    state: absent
  become: true
  when: sonarqube_remove_packages

- name: prereq repositories are installed
  package:
    name: "{{ sonarqube_packages_repos }}"
    state: "{{ sonarqube_packages_state }}"
  become: true

- name: prereq packages are installed
  package:
    name: "{{ sonarqube_packages_prereq }}"
    state: "{{ sonarqube_packages_state }}"
  become: true

- name: packages are installed
  package:
    name: "{{ sonarqube_packages_install }}"
    state: "{{ sonarqube_packages_state }}"
  become: true
